### PR TITLE
fix: bump nettle version

### PR DESCRIPTION
**Pull request by leeroyrose**

### CODE REVIEW

**Comment by kpturner** [comment]
I seem to still be updates for these things :D

**Comment by richdouglasevans** [comment]
> I seem to still be updates for these things :D

👋 Hiya Kevin, hope you're keeping safe and well.

Well darn, I'll see about sorting that.

**Comment by kpturner** [comment]
All well thanks.   Is it supposed to be public?

**Comment by leeroyrose** [comment]
Probably not? Any idea how to release this? 🤔

**Comment by richdouglasevans** [comment]
As I understand it this is a legit open source repo from Elsevier 👍

**Pull request merged**
